import { PrismaClient, AccessRole } from '@prisma/client';
import { hashSync } from 'bcryptjs';
const prisma = new PrismaClient();

async function main(){
  await prisma.activityLog.deleteMany(); await prisma.approval.deleteMany(); await prisma.report.deleteMany(); await prisma.shiftStaff.deleteMany(); await prisma.shift.deleteMany(); await prisma.action.deleteMany(); await prisma.event.deleteMany(); await prisma.booking.deleteMany(); await prisma.unit.deleteMany(); await prisma.user.deleteMany(); await prisma.employee.deleteMany(); await prisma.guest.deleteMany(); await prisma.property.deleteMany();

  const properties = await Promise.all([
    prisma.property.create({data:{name:'Uluwatu Cliff Villas',code:'UCV',type:'villa',location:'Uluwatu',address:'Jl. Labuan Sait',ownerName:'Arta Santoso',launchDate:new Date('2022-05-01'),status:'active',operatingMode:'full_service',unitCount:8,checkInTime:'14:00',checkOutTime:'12:00'}}),
    prisma.property.create({data:{name:'Canggu Courtyard Boutique Hotel',code:'CCB',type:'boutique_hotel',location:'Canggu',address:'Jl. Batu Bolong',ownerName:'Maya Wijaya',launchDate:new Date('2021-02-01'),status:'active',operatingMode:'hotel',unitCount:10,checkInTime:'15:00',checkOutTime:'11:00'}}),
    prisma.property.create({data:{name:'Sidemen Valley Retreat',code:'SVR',type:'retreat',location:'Sidemen',address:'Banjar Tebola',ownerName:'Ketut Arsana',launchDate:new Date('2020-07-10'),status:'active',operatingMode:'resort',unitCount:6,checkInTime:'14:00',checkOutTime:'12:00'}})
  ]);

  const roles:[string,AccessRole,string|null][]=[['Central Manager', 'central_manager', null],['Property Manager UCV','property_manager',properties[0].id],['Ops Head CCB','department_head',properties[1].id],['Line Staff UCV','line_staff',properties[0].id],['Finance Controller','finance',null],['Owner UCV','owner',properties[0].id],['Line Staff CCB','line_staff',properties[1].id],['Property Manager CCB','property_manager',properties[1].id],['Ops Head SVR','department_head',properties[2].id],['Line Staff SVR','line_staff',properties[2].id],['Property Manager SVR','property_manager',properties[2].id]];
  const employees=[] as any[];
  for (const [name,role,propertyId] of roles){employees.push(await prisma.employee.create({data:{fullName:name,role:name,department:'operations',accessRole:role,propertyId,phone:'+62'+Math.floor(Math.random()*999999999),email:name.toLowerCase().replace(/\s+/g,'.')+'@ops.local',employmentStatus:'active',trainingStatus:'completed'}}));}
  for (const e of employees){await prisma.user.create({data:{name:e.fullName,email:e.email,password:hashSync('password123',10),employeeId:e.id}});}

  const units=[] as any[]; for(const p of properties){for(let i=1;i<=p.unitCount;i++){units.push(await prisma.unit.create({data:{propertyId:p.id,name:`${p.code}-${i}`,code:`${p.code}${i}`,type:'suite',floorOrZone:`Zone ${Math.ceil(i/3)}`,capacity:2,readinessStatus:i%5===0?'not_ready':'ready',housekeepingStatus:'clean',maintenanceStatus:'ok',occupancyStatus:i%3===0?'occupied':'vacant'}}));}}
  const guests=[] as any[]; for(let i=1;i<=24;i++){guests.push(await prisma.guest.create({data:{fullName:`Guest ${i}`,phone:`+62812${100000+i}`,email:`guest${i}@mail.com`,language:'English',nationality:i%2?'Australia':'Indonesia',vipFlag:i%10===0,repeatGuestFlag:i%4===0}}));}
  const bookings=[] as any[]; for(let i=0;i<24;i++){const unit=units[i%units.length];bookings.push(await prisma.booking.create({data:{propertyId:unit.propertyId,unitId:unit.id,guestId:guests[i].id,channel:'direct',checkInDate:new Date(Date.now()+((i-8)*86400000)),checkOutDate:new Date(Date.now()+((i-7)*86400000)),guestCount:2,status:i%6===0?'checked_out':'confirmed',paymentStatus:'paid',depositAmount:100,totalAmount:450,currency:'USD'}}));}
  const events=[] as any[]; const types=['check_out','complaint','maintenance_issue','bad_review','inspection']; for(let i=0;i<22;i++){const b=bookings[i%bookings.length];events.push(await prisma.event.create({data:{propertyId:b.propertyId,unitId:b.unitId,guestId:b.guestId,bookingId:b.id,type:types[i%types.length] as any,severity:(['low','medium','high','critical'][i%4]) as any,source:'ops',title:`Event ${i+1}`,description:'Operational event',occurredAt:new Date(),detectedAt:new Date(),status:'open',createdByEmployeeId:employees[1].id}}));}
  for(let i=0;i<45;i++){const e=events[i%events.length];await prisma.action.create({data:{propertyId:e.propertyId,unitId:e.unitId,eventId:e.id,assignedToEmployeeId:employees[(i%employees.length)].id,type:(['housekeeping','maintenance','quality_check','guest_request'][i%4]) as any,priority:(['normal','high','urgent'][i%3]) as any,title:`Action ${i+1}`,description:'Generated action',dueAt:new Date(Date.now()+((i%6)-2)*3600000),status:i%7===0?'overdue':'assigned',requiresApproval:i%9===0,approvalStatus:i%9===0?'pending':'not_required'}});}
  const shifts=[] as any[]; for(let i=0;i<8;i++){shifts.push(await prisma.shift.create({data:{propertyId:properties[i%3].id,shiftDate:new Date(Date.now()-i*86400000),shiftType:(['morning','evening','night'][i%3]) as any,supervisorEmployeeId:employees[1].id,status:i<2?'active':'closed',handoverNotes:'Handover complete',incidentSummary:'Minor incident'}}));}
  for(const sh of shifts.slice(0,7)){for(const e of employees.slice(0,4)){await prisma.shiftStaff.create({data:{shiftId:sh.id,employeeId:e.id,roleInShift:'ops',attendanceStatus:'present'}})}}
  for(let i=0;i<6;i++){await prisma.report.create({data:{propertyId:properties[i%3].id,type:(['daily','weekly','monthly','owner'][i%4]) as any,periodStart:new Date(Date.now()-7*86400000),periodEnd:new Date(),status:'generated',generatedByEmployeeId:employees[1].id,ownerVisible:i%2===0,summary:'Report summary',kpi:{occupancy:0.75,adr:120},openRisks:'2 critical open actions'}})}
  const actionNeedsApproval=await prisma.action.findFirstOrThrow({where:{requiresApproval:true}});
  await prisma.approval.create({data:{entityType:'Action',entityId:actionNeedsApproval.id,propertyId:actionNeedsApproval.propertyId,requestedByEmployeeId:employees[3].id,approverEmployeeId:employees[0].id,approvalType:'critical_action',status:'pending',requestedAt:new Date()}});
  for(let i=0;i<20;i++){await prisma.activityLog.create({data:{employeeId:employees[i%employees.length].id,entityType:'Action',entityId:`seed-${i}`,actionType:'status_change',newValue:{status:'assigned'}}})}
}
main().finally(async()=>prisma.$disconnect());
